## EJECUTA ESTA CELDA PARA AUTENTICARTE CON TU CUENTA DE GMAIL

In [56]:
from mooclib import *
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

CLICK ON THIS LINK TO AUTHENTICATE WITH YOUR GMAIL ACCOUNT
https://accounts.google.com/o/oauth2/auth?scope=profile+email&redirect_uri=http%3A%2F%2Flocalhost%3A8080&response_type=code&client_id=486275613361-7nk9ktukfcfjevfoe3tamjp0pmbjmprs.apps.googleusercontent.com&access_type=offline
waiting for authentication ...
authentication succeeded


## Ejercicio 1: Estimadores

completa la función siguiente para que, dado `X` $\in \mathbb{R}^{n \times m}$, un dataframe de Pandas o un array `numpy` con $m$ columnas y $n$ elementos, devuelva dos vectores $\in \mathbb{R}^m$

- uno con los promedios de cada columna de `X`
- uno con las desviaciones estandar de cada columna de `X`

#### Ejemplo de ejecución

    > d = pd.read_csv("data/data_banknote_authentication.txt.gz")
    > print means_stds(d)
    > print means_stds(d.values)
    
    (array([ 0.43373526,  1.92235312,  1.39762712, -1.19165652,  0.44460641]), array([ 2.84172641,  5.86690749,  4.30845909,  2.10024732,  0.49692208]))
    (array([ 0.43373526,  1.92235312,  1.39762712, -1.19165652,  0.44460641]), array([ 2.84172641,  5.86690749,  4.30845909,  2.10024732,  0.49692208]))

In [53]:
import pandas as pd
import numpy as np

dp = pd.read_csv("../data/data_banknote_authentication.txt.gz")
dn = np.array(dp)
type(dp)
type(dn)

numpy.ndarray

In [54]:
type(dp)

pandas.core.frame.DataFrame

In [55]:
np.mean(dp)

varwt     0.433735
skewt     1.922353
curwt     1.397627
entrwt   -1.191657
class     0.444606
dtype: float64

In [59]:
a = pd.DataFrame()
if(np == type(dn)):
    print('iguales')
    
else: 
    print('diferentes')

diferentes


In [60]:
import pandas as pd
import numpy as np

def means_stds(x):
    import pandas as pd
    import numpy as np
    a = pd.DataFrame()
    if(type(x)!=type(a)):
        x = pd.DataFrame(x)
    
    m = np.mean(x).values
    s = np.std(x).values
    
    return m,s

import urllib, inspect
src1 = urllib.quote_plus(inspect.getsource(means_stds))

In [61]:
# VERIFICA TU CODIGO
d = pd.read_csv("../data/data_banknote_authentication.txt.gz")
print means_stds(d)
print means_stds(d.values)

(array([ 0.43373526,  1.92235312,  1.39762712, -1.19165652,  0.44460641]), array([ 2.84172641,  5.86690749,  4.30845909,  2.10024732,  0.49692208]))
(array([ 0.43373526,  1.92235312,  1.39762712, -1.19165652,  0.44460641]), array([ 2.84172641,  5.86690749,  4.30845909,  2.10024732,  0.49692208]))


#### evaluate your answer before submitting:

In [62]:
!./run CHECK_SOLUTION PS3_1 $src1

evaluation result CORRECT


#### submit your answer (you must be connected to internet)

In [65]:
!./run SUBMIT_SOLUTION PS3_1 $src1

connecting ... registering submission for oscarcorzog@gmail.com ...
your submissions sheet is https://docs.google.com/spreadsheets/d/1gYXo5A4KBV9PRukEwg-5-97vBwB_Tc3SHVDnMWoiEL4
----
evaluation result CORRECT , submission registered


## Ejercicio 2: $\mu$, $\sigma$ por clase

Completa la función siguiente para que, por cada valor distinto de $y$ devuelva una lista de promedios y desviaciones estandar de cada columna de la porción de $X$ correspondiente a cada valor de y.

La función a de devolver dos diccionarios python. Uno con las medias y otro con las desviaciones estandar para cada columna y para cada clave. Cada diccionario tendrá como claves los valores presentes en $y$.

#### Ejecución de ejemplo:

Para el siguiente $X$ e $y$:

          X      y
        ------  ---
        [7, 8]   2
        [1, 9]   1
        [2, 4]   0
        [7, 3]   2
        [8, 8]   1
        [6, 6]   1
        [8, 0]   0
        [6, 9]   1
        [3, 5]   0|
        [1, 8]   1

La salida ha de ser:

    > m,s = means_stds_perclass(X,y)
    > print "means", means
    > print "stds ", stds
    
    means {0: array([ 4.33333333,  3.        ]), 1: array([ 4.4,  8. ]), 2: array([ 7. ,  5.5])}
    stds  {0: array([ 2.62466929,  2.1602469 ]), 1: array([ 2.87054002,  1.09544512]), 2: array([ 0. ,  2.5])}

In [91]:
x = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1])

a = pd.DataFrame(x)
a['y'] = y
a

0  1  y
0  7  8  2
1  1  9  1
2  2  4  0
3  7  3  2
4  8  8  1
5  6  6  1
6  8  0  0
7  6  9  1
8  3  5  0
9  1  8  1

In [111]:
y.shape[0]

10

In [125]:
l0 = []
l1 =[]
l2 = []
for i in range(3):
    if(i==0):
        for j in range(y.shape[0]):
            if(y[j]==i):
                l0.append(x[j])
                    
    else:
        if(i==1):
            for j in range(y.shape[0]):
                if(y[j]==i):
                    l1.append(x[j])
        else:
            for j in range(y.shape[0]):
                if(y[j]==i):
                    l2.append(x[j])

cero = np.std(np.array(l0),0)
uno = np.std(np.array(l1),0)
dos = np.std(np.array(l2),0)


l = [cero, uno, dos]
f = np.array(l)
f.shape

(3, 2)

In [116]:
b=a.groupby('y').agg(['mean','std'])
b

0              1          
       mean       std mean       std
y                                   
0  4.333333  3.214550  3.0  2.645751
1  4.400000  3.209361  8.0  1.224745
2  7.000000  0.000000  5.5  3.535534

In [100]:
c = b.values
dic={}
for i in range(b.shape[0]):
    dic[i] = c[i]
dic

{0: array([ 4.33333333,  3.21455025,  3.        ,  2.64575131]),
 1: array([ 4.4       ,  3.20936131,  8.        ,  1.22474487]),
 2: array([ 7.        ,  0.        ,  5.5       ,  3.53553391])}

In [2]:
def means_stds_perclass(x,y):
    import pandas as pd
    import numpy as np
    
    a = pd.DataFrame(x)
    a['y'] = y
    
    b = a.groupby('y').agg(['mean']).values
    dm = {}
    for i in range(b.shape[0]):
        dm[i] = b[i]
    
    l0 = []
    l1 =[]
    l2 = []
    for i in range(3):
        if(i==0):
            for j in range(y.shape[0]):
                if(y[j]==i):
                    l0.append(x[j])
        else:
            if(i==1):
                for j in range(y.shape[0]):
                    if(y[j]==i):
                        l1.append(x[j])
            else:
                for j in range(y.shape[0]):
                    if(y[j]==i):
                        l2.append(x[j])

    cero = np.std(np.array(l0),0)
    uno = np.std(np.array(l1),0)
    dos = np.std(np.array(l2),0)


    #l = [cero, uno, dos]
    #f = np.array(l)
    ds={0:cero, 1:uno, 2:dos}
    #for i in range(f.shape[0]):
        #ds[i] = f[i]
    
    return dm, ds

import urllib, inspect
src2 = urllib.quote_plus(inspect.getsource(means_stds_perclass))

In [130]:
# VERIFICA TU CODIGO
X = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1])
means,stds = means_stds_perclass(X,y)
print "means", means
print "stds ", stds

means {0: array([ 4.33333333,  3.        ]), 1: array([ 4.4,  8. ]), 2: array([ 7. ,  5.5])}
stds  {0: array([ 2.62466929,  2.1602469 ]), 1: array([ 2.87054002,  1.09544512]), 2: array([ 0. ,  2.5])}


#### evaluate your answer before submitting:

In [131]:
!./run CHECK_SOLUTION PS3_2 $src2

/opt/miniconda/lib/python2.7/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/opt/miniconda/lib/python2.7/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/opt/miniconda/lib/python2.7/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
evaluation result NOT CORRECT


#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_2 $src2

## Ejercicio 3: Probabilidad conjunta para una clase

completa la función siguiente para que dado

- $X \in \mathbb{R}^{n\times m}$ = $\{ x_1, ..., x_n\}$, con $x_i \in \mathbb{R}^m$ = $\{x_{i,1},...,x_{i,m}\}$
- $m \in \mathbb{R}^m$ un vector con un $\mu$ para cada columna de $X$
- $s \in \mathbb{R}^m$ un vector con un $\sigma$ para cada columna de $X$

devuelva un vector $P \in\mathbb{R}^{n}$ = $\{p_1,...,p_n\}$

de forma que:

$$p_i = \prod_{k=1}^m P_{\mu_k,\sigma_k}(x_{i,k})$$

en donde

$P_{\mu_k,\sigma_k}(x_{i,k})$ es la probabilidad de $x_{i,k}$ según una distribución normal con media $\mu_k$ y desviación estándar $\sigma_k$

El resultado ha de ser un array numpy

#### Ejecución de ejemplo

Para $X$ como en el ejemplo del ejercicio anterior y $m=[4,5]$ y $s=[4,2]$ el resultado debería de ser el siguiente:

    > prob(X, m, s)

    array([ 0.00487532,  0.00203234,  0.01549375,  0.00910831,  0.00391743,
            0.01549375,  0.00053017,  0.00237604,  0.01928228,  0.00487532])
            
**Sugerencia**: usa el método `pdf` de [`scipy.stats.norm`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html) para calcular $P_{\mu_k,\sigma_k}(x_{i,k})$

In [ ]:
def prob(X, m, s):
    import scipy.stats as stats
    
    #Escribe tu código AQUI!!
    
    
    return result

import urllib, inspect
src3 = urllib.quote_plus(inspect.getsource(prob))

In [ ]:
X = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1])
m = np.r_[4,5]
s = np.r_[4,2]
prob(X, m, s)

In [5]:
import pandas as pd
import numpy as np

m = np.r_[4,5]
m

array([4, 5])

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_3 $src3

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_3 $src3

## Ejercicio 4: Cálculo de la proporcion de elementos de cada clase

Completa la función siguiente para que, dado un $y$, devuelva un diccionario con la proporcion de elementos existentes para cada valor distinto de $y$

#### Ejecución de ejemplo

    > y = [2 1 0 2 1 1 0 1 0 1]
    > props(y)
    
    {0:0.3, 1:0.5, 2:0.2}

In [40]:
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1])
unico = []
for i in y:
    if i not in unico:
        unico.append(i)
orden = sorted(unico)
orden

[0, 1, 2]

In [51]:
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1,0,2,1])
unico = []
a=0
b=[]
for i in y:
    if i not in unico:
        unico.append(i)
orden = sorted(unico)
for i in orden:
    for j in y:
        if(i==j):
            a=a+1
    b.append(a)
    a=0
c=[]
for i in b:
    c.append(i/(y.shape[0]*1.))
d={}
for i in range(len(orden)):
    d[orden[i]]=c[i]
    
d

{0: 0.3076923076923077, 1: 0.46153846153846156, 2: 0.23076923076923078}

In [53]:
def props(y):
    unico = []
    a=0
    b=[]
    for i in y:
        if i not in unico:
            unico.append(i)
    orden = sorted(unico)
    for i in orden:
        for j in y:
            if(i==j):
                a=a+1
        b.append(a)
        a=0
    c=[]
    for i in b:
        c.append(i/(y.shape[0]*1.))
    d={}
    for i in range(len(orden)):
        d[orden[i]]=c[i]
    return d

import urllib, inspect
src4 = urllib.quote_plus(inspect.getsource(props))

In [54]:
# VERIFICA TU CODIGO
y = np.array([2, 1, 0, 2, 1, 1, 0, 1, 0, 1])
print props(y)

{0: 0.3, 1: 0.5, 2: 0.2}


#### evaluate your answer before submitting:

In [55]:
!./run CHECK_SOLUTION PS3_4 $src4

evaluation result CORRECT


#### submit your answer (you must be connected to internet)

In [57]:
!./run SUBMIT_SOLUTION PS3_4 $src4

connecting ... registering submission for oscarcorzog@gmail.com ...
your submissions sheet is https://docs.google.com/spreadsheets/d/1gYXo5A4KBV9PRukEwg-5-97vBwB_Tc3SHVDnMWoiEL4
----
evaluation result CORRECT , submission registered


## Ejercicio 5: Clase API sklearn

ensambla las funciones de los ejercicios anteriores en una clase conforme al API de machine learning de sklearn según se describe en el código siguiente.

#### Ejecución de ejemplo

El siguiente código

    > X = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
    > y = np.array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1])

    > b = Bayes()
    > b.fit(X,y)
    > print b.predict(X)
    > print b.score(X,y)
    
debe de arrojar el siguiente resultado

    [1 1 0 0 1 1 0 1 1 1]
    0.7  

In [ ]:
def Bayes(**args): # hack for inspect to work with classes
    from scipy.optimize import minimize
    import numpy as np
    
    class Bayes_class:
        def fit(self, X, y):
            # ESCRIBE TU CÓDIGO AQUÍ
            self.means = ...
            self.stds  = ...
            self.props = ...

        def predict(self, X):
            
            # TU CÓDIGO AQUÍ
            # usa el código del ejercicio 4 para elegir, para cada fila de X, 
            # la clase que mas probabilidad tenga
            
            predictions = ...
            
            return predictions
                
        def score(self, X, y):
            return np.mean(y==self.predict(X))
        
    return Bayes_class(**args)

import urllib, inspect
src5 = urllib.quote_plus(inspect.getsource(Bayes))

In [ ]:
# VERIFICA TU CODIGO
import numpy as np
X = np.array([[7, 8],[1, 9],[2, 4],[7, 3],[8, 8],[6, 6],[8, 0],[6, 9],[3, 5],[1, 8]])
y = np.array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1])

b = Bayes()
b.fit(X,y)
print "mi codigo"
print b.predict(X)
print b.score(X,y)

from sklearn.naive_bayes import GaussianNB
g = GaussianNB()
g.fit(X,y)
print "\nsklearn"
print g.predict(X)
print g.score(X,y)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_5 $src5

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_5 $src5

---
# <center> Thanks! </center>