## Problem Set 01 Introducción a Python

## EJECUTA ESTA CELDA PARA AUTENTICARTE CON TU CUENTA DE GMAIL

In [3]:
from mooclib import *
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

CLICK ON THIS LINK TO AUTHENTICATE WITH YOUR GMAIL ACCOUNT
https://accounts.google.com/o/oauth2/auth?scope=profile+email&redirect_uri=http%3A%2F%2F127.0.0.1%3A8080&response_type=code&client_id=486275613361-7nk9ktukfcfjevfoe3tamjp0pmbjmprs.apps.googleusercontent.com&access_type=offline
waiting for authentication ...
code=4/WwDDYAZDhbVW2L5S45bsGcuBa-vJmVGkqU9ayif5vmh0WELZLUWH4saMZ9_PzYa6YTEiEr1PztZApJHJLplZwSE&scope=https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email
No authentication


## <font style="color: red"> Esta práctica contiene 4 ejercicios <!-- ONLY IN NOTEBOOK -->

### Ejercicio 1: Generación de una matriz

Completa la función `single_value_matrix` para que devuelva una matriz de tamaño $n\_rows \times n\_cols$ con todos los elementos igual a $value$. Ejecuta y depura tu código con entradas de prueba, verifica que la salida es la esperada y prueba con nuevos valores.

#### Ejemplo de ejecución

    > single_value_matrix(n_rows=3, n_cols=4, value=5)
    
      [[ 5.  5.  5.  5.]
       [ 5.  5.  5.  5.]
       [ 5.  5.  5.  5.]]
     
_Sugerencia_: Usa la función `np.ones` de Numpy [[ref](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)]

In [ ]:
import numpy as np

def single_value_matrix(n_rows, n_cols, value):
    ## --- TU CODIGO AQUI ---
    result = ???
    return result

import urllib, inspect
src1 = urllib.quote_plus(inspect.getsource(single_value_matrix))

In [ ]:
# -- VERIFICA TU CODIGO --
print single_value_matrix(n_rows=3, n_cols=4, value=5)
print single_value_matrix(n_rows=4, n_cols=2, value=3.45)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS1_1 $src1

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS1_1 $src1

### Ejercicio 2: Suma de diferencias cuadradas de matrices

Dadas dos matrices de igual tamaño, $A \in \mathbb{R}^{m\times n}$ y $B \in \mathbb{R}^{m\times n}$ la suma de las diferencias cuadradas entre los elementos de la matriz se define por:


$$sum\_squared\_difference(A,B) = \sum_{i=0}^m \sum_{j=0}^n (a_{ij} - b_{ij})^2$$


donde $a_{ij}$ es el elemento de la fila $i$ y columna $j$ de la matriz $A$. Completa la función `sum_squared_difference` con esta definición.


#### Ejemplo de ejecución

    > A = np.array([[1,2],[3,4]])
    > B = np.array([[0,3],[4,6]])
    > sum_squared_difference(A,B)
    
      7
      
_Sugerencia_ Usa la función `np.sum` de Numpy [[ref](http://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html)]

In [ ]:
import numpy as np

def sum_squared_difference(A,B):
    ## --- TU CODIGO AQUI ---
    result = ???
    return result

import urllib, inspect
src2 = urllib.quote_plus(inspect.getsource(sum_squared_difference))

In [ ]:
# VERIFICA TU CODIGO
A = np.array([[1,2],[3,4]])
B = np.array([[0,3],[4,6]])
print sum_squared_difference(A,B)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS1_2 $src2

In [ ]:
!./run SUBMIT_SOLUTION PS1_2 $src2

### Ejercicio 3: Pandas Dataframe

Completa la función `create_dataframe` para que dado un numpy array `A` como argumento:

- devuelva un dataframe de pandas con los contenidos de `A`
- las columnas del dataframe han de llamarse `col_1`, `col_2`, etc.
- los índices del mismo han de ser consecutivos empezando en el número 100.
- el dataframe ha de incluir una columna adicional llamada `promedio` que contenga, para cada fila de `A`, el promedio de sus elementos.


**Ejemplo de ejecución**
    > A = np.array([[1,2,3],[3,4,5]])
    > create_dataframe(A)
    
|   | col_1  |  col_2 | col_3  | promedio  |
|---|---|---|---|---|
|100   | 1  |  2 | 3  |  2.0 |
|101   | 3  |  4 |  5 |   4.0 |

In [ ]:
def create_dataframe(A):
    import numpy as np
    import pandas as pd
    
    # TU CODIGO AQUI ----
    ?? 
    ??
    ??
    return result

import urllib, inspect
src3 = urllib.quote_plus(inspect.getsource(create_dataframe))

In [ ]:
## VERIFICA TU CODIGO
A = np.array([[1,2,3],[3,4,5]])
create_dataframe(A)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS1_3 $src3

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS1_3 $src3

### Ejercicio 4: Pandas group by


completa la función siguiente para que, dado un dataframe A:
    
- agrupe los valores por la columns `col1`.
- por cada columna restante calcule la media y la desviación estandar de los grupos resultantes.

**Ejecución de ejemplo**

    A = 

|   | col_1  |  col_2 | col_3  |
|---|---|---|---|
|0   | 0  |  1 |  0 |  
|1   | 3  |  3 |  3 |  
|2   | 1  |  3 |  3 |  
|3   | 0  |  1 |  3 |  
|4   | 3  |  1 |  2 |  


    > group_agg(A)
   
 
|  col1     | col_2<br/>mean |  <br/>std    | col_3<br/>mean |<br/>std     |
|---|---|---|---|---|
|0   | 1  |  0.000000 |  1.5 | 2.121320|  
|1   | 3  |  NaN  |  3.0 | NaN |  
|3   | 2  |  1.414214 |  2.5 | 0.707107|  

**HINT**: Fíjate en el ejemplo de la función `agg` de `groupby` de [la documentación en línea](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.DataFrameGroupBy.agg.html) y usa las funciones de numpy `np.mean` y `np.std`

In [ ]:
def group_agg(A):
    import numpy as np
    import pandas as pd
    
    result = ???
    
    return result

import urllib, inspect
src4 = urllib.quote_plus(inspect.getsource(group_agg))

In [1]:
# VERIFICA TU CODIGO
import pandas as pd
import numpy as np
A = pd.DataFrame(np.array([[0,1,0],[3,3,3],[1,3,3],[0,1,3],[3,1,2]]), columns=["col1", "col2", "col3"])
group_agg(A)

NameError: name 'group_agg' is not defined

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS1_4 $src4

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS1_4 $src4